### ISSUE TITLE
Your onboard programmable RGB led example fails. (wrong pin number specified)

### ISSUE THREAD

**Issue by donwade** [Freenove/Freenove_ESP32_S3_WROOM_Board#10]
Your onboard RGB led is a neat feature that I think many will overlook but your supplied example is incorrect.

#include "Freenove_WS2812_Lib_for_ESP32.h"                                             
  2 
  3 #define LEDS_COUNT  8
  4 **#define LEDS_PIN    48**  // 2  is incorrect!!!
  5 #define CHANNEL     0
  6 
  7 Freenove_ESP32_WS2812 strip = Freenove_ESP32_WS2812(LEDS_COUNT, LEDS_PIN, CHANNEL, TYPE
  8

**Comment by Zhentao-Lin** [comment]
Freenove_WS2812_Lib_for_ESP32.zip is not designed for ESP32S3. In fact, it is designed for Freenove_ESP32_WROVER_Board. LEDS_PIN is also used for ESP32.
