### ISSUE TITLE
Sketch_07.1_CameraWebServer.cpp:104:15: error: 'class WiFiClass' has no member named 'STA'

### ISSUE THREAD

**Issue by AncientTree** [Freenove/Freenove_ESP32_S3_WROOM_Board#12]
`Freenove_ESP32_S3_WROOM_Board/C/Sketches/Sketch_07.1_CameraWebServer/Sketch_07.1_CameraWebServer.ino`
When I Build, Error message like this:
```
src/Sketch_07.1_CameraWebServer.cpp: In function 'void setup()':
src/Sketch_07.1_CameraWebServer.cpp:103:15: error: 'class WiFiClass' has no member named 'hasIP'; did you mean 'dnsIP'?
   while (WiFi.hasIP() != true) {
               ^~~~~
               dnsIP
```
line 102
```C++
while (WiFi.STA.hasIP() != true) {
  Serial.print(".");
  delay(500);
}
```
 error: 'class WiFiClass' has no member named 'STA'

Any idea for resolve this?

**Comment by AncientTree** [comment]
Replace those lines to

``` Cpp
  while (WiFi.localIP().toString() == "0") {
    Serial.print("IP："+WiFi.localIP().toString());
    delay(500);
  }
```
solve the problem, please update the example.

**Comment by Zhentao-Lin** [comment]
The WiFi.STA.hasIP() function appears on Arduino ESP32 V3.0.x, but if you're using V2.0.x, it will get an error.

**Comment by AncientTree** [comment]
> The WiFi.STA.hasIP() function appears on Arduino ESP32 V3.0.x, but if you're using V2.0.x, it will get an error.

Thank you. How could I alter Arduino ESP32 V2.0.X to V3.0.X? I use VS Code + PlatformIO. PlatformIO seem never ask me to select😇

**Comment by Zhentao-Lin** [comment]
Because platformio has not been updated to V3.0.x, it is not supported.
