### ISSUE TITLE
Flash and PSRAM size

### ISSUE THREAD

**Issue by anuraj-rp** [Freenove/Freenove_ESP32_S3_WROOM_Board#3]
Hi,

Which version of WROOM is the board using? What is the size of PSRAM and Flash on the devkit?

**Comment by gruenfron** [comment]
Hi,
on my module the last line of the imprinted text on the lid reads MON8R8 which points to 8MB FLASH and 8MB PSRAM (See pg. 3 of the WROOM Datasheet).

**Comment by anuraj-rp** [comment]
Hi,

Ok, thanks. This issue can be closed
