### ISSUE TITLE
How Can I auto Start the Stream??

### ISSUE THREAD

**Issue by cohen-sydney** [Freenove/Freenove_ESP32_S3_WROOM_Board#5]
Id Love to have the stream Auto start, can you advise how I can implement that??

I want to get my HomeBridge Server to access the Stream, in connecting via HomeBridge FFmpeg, I do that by a simple HTTP request.

**Comment by Zhentao-Lin** [comment]
Please send email:  support@freenove.com

**Comment by cohen-sydney** [comment]
thanks will do.
